### ISSUE TITLE
Transaction is not completed

### ISSUE THREAD

**Issue by triodesk** [chafey/ethereum-private-network#2]
I have initiated the transaction, it is getting success. But the balance is not reduced in from account and increaed in the to accouns. Any other configuration i need to do .

**Comment by chafey** [comment]
I just followed the steps listed in the readme and it worked exactly as it should.  Are you doing something different?  Really hard to help without more detail

**Comment by chafey** [comment]
Any update on this?  Will close if I don't hear back soon
